import numpy as np
arr = np.array([1, 2, 3])
print(arr)
arr1 = np.arange(1, 6)
print(arr1)
arr2 = np.zeros(3)
print(arr2)
arr3 = np.ones(3)
print(arr3)
arr4 = np.linspace(0, 1, 5)
print(arr4)
arr5 = np.random.rand(3)
print(arr5)
arr6 = np.random.randint(0, 10, 5)
print(arr6)
arr7 = np.array([1, 2, 3])
max_value = np.max(arr7)
print(max_value)
arr8 = np.array([1, 2, 3])
min_value = np.min(arr7)
print(min_value)
arr9 = np.array([1, 2, 3])
mean_value = np.mean(arr9)
print(mean_value)
ar1 = np.array([1, 2, 3])
median_value = np.median(ar1)
print(median_value)
ar2 = np.array([1, 2, 3])
ar3 = np.array([1, 2, 3])
dot_product=np.dot(ar2,ar3)
print(dot_product)
